### ISSUE TITLE
Suggestion: Watering Can use on modded farmland

### ISSUE THREAD

**Issue by Rayxanber** [mim1q/ConvenientDecor#5]
Hello! It doesn't seem like the watering can works on modded farmland, such as Rich Soil from Farmer's Delight. Are there any plans on making this compatible?

**Comment by mim1q** [comment]
Hey - sorry for not responding. If those farmlands were inheriting from the vanilla `FarmlandBlock` class, this should probably work (can't guarantee that tho). Otherwise there's not really much I can do without digging into those mods' code 😅

If I ever find some better solution I'll reopen this issue 👍
